%YAML:1.0
---
Debug_mode: 1
Camera_device: 1
Resolution_camera: [ 640, 480 ]
Projection_top_left: [ 179., 114. ]
Projection_top_right: [ 485., 116. ]
Projection_bottom_left: [ 169., 284. ]
Projection_bottom_right: [ 493., 295. ]
Meter_camera: 7.2173400878906250e+01
Resolution_projector: [ 1920, 1200 ]
Fullscreen_projector: 1
Meter_projector: 4.2961791992187500e+02
Maximum_FPS_scene: 60
Frames_projector_camera_delay: 5
Projector_background_light: 3.8999998569488525e-01
FPS_capture_scene: 8
Iterations_delay_peopleextracting: 0
Factor_resize_capture_scene: 10
Minimum_Area_Blobs: 100
Minimum_Distance_Between_Blobs: 50
